apiVersion: v1
kind: Service
metadata:
  name: lada
  labels:
    app: lada
spec:
  type: ClusterIP
  selector:
    app: lada
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP

